### ISSUE TITLE
Pre-unix epoch dates

### ISSUE THREAD

**Issue by richard-srnsw** [propublica/timeline-setter#10]
I was building a timeline spanning the nineteenth and twentieth centuries and hit a snag with the to_json method. I couldn't get any of my pre-1970 dates past the call to Time.parse("...") which makes the timestamps (I am on Ruby 1.8.7).
I saw that the timelines themselves handle pre-1970 (negative) timestamps & I got my 19C to 20C timeline working by adding the following code:

<pre>
    # Convert human dates to timestamps, sort the hash by timestamp, and
    # convert the events hash to JSON to stick into our HTML.
    def to_json
      @events.each {|r| r[:timestamp] = timeline_timestamp(r[:date])}
      @events.to_json
    end
    
     # if earlier than 1970, make a negative timestamp
     def timeline_timestamp(date)
      epoch = Date.parse("1970-01-01")
      input = Date.parse(date)
      if epoch > input
        (epoch - input).to_i * (60 * 60 * 24) * -1000 
      else
        Time.parse(date).to_i * 1000
      end
    end
</pre>

Thanks ProPublica for releasing a great tool

**Comment by ashaw** [comment]
It seems to be working on our end in 1.8.7:

```
irb(main):002:0> require 'time'
=> true
irb(main):003:0> Time.parse "Aug 15, 1950"
=> Tue Aug 15 00:00:00 -0400 1950
irb(main):004:0> Time.parse("Aug 15, 1950").to_i
=> -611611200
```

Could you paste a stack trace?

**Comment by richard-srnsw** [comment]
This must be a Windows-specific thing, I should have mentioned it before, I was ashamed!

<pre>
irb(main):001:0> require 'time'
=> true
irb(main):002:0> Time.parse "Aug 15, 1950"
ArgumentError: argument out of range
    from C:/RailsInstaller/Ruby1.8.7/lib/ruby/1.8/time.rb:184:in `local'
    from C:/RailsInstaller/Ruby1.8.7/lib/ruby/1.8/time.rb:184:in `make_time'
    from C:/RailsInstaller/Ruby1.8.7/lib/ruby/1.8/time.rb:243:in `parse'
    from (irb):2
</pre>

Happy for you to close this. Since pre-epoch dates do work, if any other Windows users encounter this it is perhaps more appropriate to stick my Windows workaround in a rescue block.

<pre>
def timeline_timestamp(date)
  begin
    Time.parse(date).to_i * 1000
  rescue
    epoch = Date.parse("1970-01-01")
    input = Date.parse(date)
    if epoch > input
        (epoch - input).to_i * (60 * 60 * 24) * -1000 
    else
        raise "Can't parse date: #{input}"
    end
  end
end
</pre>

Thanks for looking at this.
