### ISSUE TITLE
A "week" interval would be nice.

### ISSUE THREAD

**Issue by palewire** [propublica/timeline-setter#11]

**Comment by palewire** [comment]
I tried out some methods like so, and I'm getting close. Patch coming, perhaps.

<pre><code>
    getWeekFloor : function(date) {
      loopDate = new Date();
      loopDate.setTime(date.valueOf());
      while (true) {
        if (loopDate.getDay() === 0) {
          break;
        } else {
          loopDate.setTime(loopDate.valueOf() - 86400000);
        }
      }
      console.log("floor: " + date + " -> " + loopDate)
      return loopDate;
    },
    
    getWeekCeil : function(date) {
      loopDate = new Date();
      loopDate.setTime(date.valueOf());
      while (true) {
        if (loopDate.getDay() === 0) {
          break;
        } else {
          loopDate.setTime(loopDate.valueOf() + 86400000);
        }
      }
      console.log("ceil: " + date + " -> " + loopDate)
      return loopDate;
    },
</code></pre>

**Comment by thejefflarson** [comment]
Ok take a look at:

https://github.com/propublica/timeline-setter/blob/master/public/javascripts/timeline-setter.js#L284

I think I fixed it. Let me know.
