### ISSUE TITLE
What ought to be done when two events fall on the same timestamp?

### ISSUE THREAD

**Issue by palewire** [propublica/timeline-setter#15]
A nudge?

**Comment by thejefflarson** [comment]
We haven't really thought about it much b/c there's now way to cleanly get around it. When there were 2 events on our timeline we produced we collapsed them into another series...

**Comment by palewire** [comment]
But if they're in two different series, isn't only one of them visible as you scroll through the timeline?

Another hack is to make a fake timestamp that is slightly lower for one event and giving them distinct display dates. I can think of several other potential ways of addressing the issue:
- Training the computer to detect identical timestamps and slightly "nudge" them apart.
- Somehow splitting the bar or otherwise "clustering" notches with identical timestamps.

It's not a huge deal right now, but I think it's something that has to be dealt with sometime.

**Comment by thejefflarson** [comment]
I meant that we put the events that happened on one day into a single card -- I think that's the right way to do it in a timeline...
