### ISSUE TITLE
The demo is serving js from github: bad for FF+NoScript & IE9

### ISSUE THREAD

**Issue by pmontrasio** [propublica/timeline-setter#18]
To make a long story short, you should serve the js files from your server and not from github. Here are the details.

I tried the demo with FF 4.0.1 Linux with NoScript 2.1.0.3 disabled: all ok.
If I enable NoScript it doesn't work even if I allow github and twitter in NoScript and even if I "Allow Scripts Globally".
This is the error I get:

Error: twttr is not defined
Source File: http://propublica.github.com/timeline-setter/doc/twitter-demo.html
Line: 65

Apparently it doesn't get https://github.com/bcherry/twitter-text-js/raw/master/twitter-text.js
I wondered if it might be an issue with NoScript. I looked on their forum and found this thread http://forums.informaction.com/viewtopic.php?f=7&t=6016&hilit=https+github#p26106
Basically, you shouldn't server .js files from your repository on github as github adds a X-Content-Type-Options: nosniff header to the response, which is also marked as Content-Type: text/plain; charset=utf-8
. My understanding is that github is intentionally marking it as plain/text and not text/javascript. That's because some browsers don't trust the js code in the body of those responses. Anybody can put js files on github and probably they don't want to give their blessing to arbitrary code they can't check.

Firefox with NoScript is one of those browsers. Even allowing all scripts doesn't make it load the js. IE9 seems to be another one (http://blogs.msdn.com/b/ie/archive/2010/10/26/mime-handling-changes-in-internet-explorer.aspx) but I can't test it. Chromium happily loads the file. I didn't check with Opera.

**Comment by thejefflarson** [comment]
I hear you on this. But since it's just a demo and not production code, we'll leave it as is.
