### ISSUE TITLE
What's the chances of this working without <!DOCTYPE html>?

### ISSUE THREAD

**Issue by palewire** [propublica/timeline-setter#2]

**Comment by ashaw** [comment]
The non-minified version does have a DOCTYPE. The minified version is designed to be embedded within another page, so we chose to omit DOCTYPE, head and body. Maybe we should wrap it on the minified example page, though.

**Comment by thejefflarson** [comment]
It'll work, see the doctype here: http://www.propublica.org/special/tbi-psycho-platoon-timeline
