### ISSUE TITLE
Year-Only Dates

### ISSUE THREAD

**Issue by jkeefe** [propublica/timeline-setter#20]
If the "date" is just a year, timeline-setter fails -- because Time.parse() fails. 

Does it make sense to have TS catch this and default to January 1 -- or July 1 -- when there's only a year in the "date" column? My experience with editorial folks building timelines in spreadsheets is this is cropping up a lot.

John

**Comment by ashaw** [comment]
I'm not sure it's such a good idea to be mucking around with Time.parse.. it gets to be a slippery slope to pave over those edge cases, and the behavior is much clearer if we support only what Time.parse does.
