### ISSUE TITLE
Years before 1900

### ISSUE THREAD

**Issue by ghost** [propublica/timeline-setter#25]
Hello everyone. I would like to add years such as 1300 but I am always getting an error while trying to make the html file. Does anyone know how can I fix this error? Do I have to change something in a function?

Thank you for your answer.

**Comment by ashaw** [comment]
Can you post the error here? Dates after the year 0 should work fine.

**Comment by ghost** [comment]
Yes of course. So I have a csv and when I write 

date,display_date,description,link,,series,html
"Jan. 1, 1348","1348","Black Death",,,14t century,"<img src=""http://static.howstuffworks.com/gif/black-death-1.jpg"" width=""300"" height=""250"">"

and it shows me these errors,

sv -o /home/christina/timeline/
/usr/lib/ruby/1.8/time.rb:184:in `local': time out of range (ArgumentError)
    from /usr/lib/ruby/1.8/time.rb:184:in`make_time'
    from /usr/lib/ruby/1.8/time.rb:243:in `parse'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/timeline.rb:14:in`to_json'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/timeline.rb:14:in `each'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/timeline.rb:14:in`to_json'
    from (erb):24:in `tmpl'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/timeline.rb:46:in`tmpl'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/timeline.rb:23:in `timeline_markup'
    from (erb):10:in`tmpl'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/timeline.rb:46:in `tmpl'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/timeline.rb:30:in`timeline'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/cli.rb:63:in `send'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/cli.rb:63:in`html'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/cli.rb:83:in `compile!'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/cli.rb:82:in`open'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/cli.rb:82:in `compile!'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/cli.rb:50:in`parse_options!'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/lib/timeline_setter/cli.rb:7:in `initialize'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/bin/timeline-setter:9:in`new'
    from /usr/lib/ruby/gems/1.8/gems/timeline_setter-0.2.0/bin/timeline-setter:9
    from /usr/bin/timeline-setter:19:in `load'
    from /usr/bin/timeline-setter:19

but when I write for example

date,display_date,description,link,,series,html
"Jan. 1, 1908","1908","The first mass car - the 'T' model of Henry Ford",,,20ος αιώνας,"<img src=""http://upload.wikimedia.org/wikipedia/commons/e/ee/Ford_Modell-T_side_20020707.jpg"" width=""300"" height=""250"">"

everything works fine. :S

Thank you for your help.

**Comment by ghost** [comment]
I mean that for years after 1901 everything is ok.

**Comment by ashaw** [comment]
Which version of Ruby are you running?

I took those two spreadsheet lines, and here's what I got:

```
$ timeline-setter -c timeline.csv
== Files copied to /Users/ashaw/rails/ts-1348-test/
```

![timeline](http://f.cl.ly/items/1Y2i390F1w0L1N3q2q3Q/Screen%20shot%202011-10-14%20at%204.40.01%20PM.png)

([bigger](http://cl.ly/1c1b0C253S3u2S2e0x17))

You may want to pass in a custom interval, so dates don't smush together on the bar, but besides that, it seems to work.

**Comment by ghost** [comment]
ruby1.8.7.302-2

**Comment by laurenrabaino** [comment]
So, what was the answer to this?
