### ISSUE TITLE
Is it possible to override .TS-item_label width?

### ISSUE THREAD

**Issue by palewire** [propublica/timeline-setter#3]
I see it's hardcoded in timeline-setter.js around line 640 with:

<pre><code>      var max = _.max(_.toArray(this.$(".TS-item_user_html").children()), function(el){ return $(el).width(); });
      if($(max).width() > 150){
        this.$(".TS-item_label").css("width", $(max).width());
      } else {
        this.$(".TS-item_label").css("width", 150);
      }</code></pre>

**Comment by thejefflarson** [comment]
Yeah that's an awful ie hack, let me see if I can clean that up and revisit it tomorrow.

**Comment by thejefflarson** [comment]
Fixed in:

https://github.com/propublica/timeline-setter/commit/c346562a65d920cefed08e2f7b8bdb908b42668e

Short answer: Muck about with `.TS-item_year`s width if you want to change the label's width.
