### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by KwadroNaut** [propublica/timeline-setter#35]
Currently I've translated public/javascripts/templates/card.jst and public/javascripts/templates.js Instead of literally adapting the strings I need to translate and merging my differences whenever there's an update I'd like to use a better way to do this, while still maintaining the current KISS approach.

**Comment by ashaw** [comment]
Have you looked at the `formatter` option? Take a look at [this](http://propublica.github.com/timeline-setter/) and scroll down to Configuring the Timeline JavaScript Embed. Let me know if there's something you want to localize that you can't do with a formatter.

**Comment by KwadroNaut** [comment]
'Read More' is hardcoded, unless I've overlooked it?

**Comment by ashaw** [comment]
Ah, good point. I should add that to the formatter function.

**Comment by thejefflarson** [comment]
You can change the the card's template now by listening to the onCardAdd event.
