### ISSUE TITLE
problems embedding non-Flash YouTube viewer in cards

### ISSUE THREAD

**Issue by tommeagher** [propublica/timeline-setter#37]
I’m building my first Timeline-Setter timeline for a features project that’s running next week. I’m trying to embed YouTube videos in the timeline events.

If I try to use the new embed code for YouTube’s iframe, it acts strangely. In this case, if I click to the next item, the audio continues playing. When I click back to the video, it’s a blank screen and won’t give me any commands to stop the audio.

If I use the old, flash-based YouTube embed code it works fine. But it’s flash, which I’m reluctant to use to avoid leaving iPad readers in the cold.

Do you know, what can I do to get the regular YouTube iframe to work?

**Comment by thejefflarson** [comment]
Hmm, I'm seeing the audio bug, but I can stop the video if I go back, which browser are you seeing this in?

**Comment by tommeagher** [comment]
Chrome 17.0.963.78

**Comment by tommeagher** [comment]
Jeff,
I put a test up here with an iframed YouTube video in the first card: 
http://data.nsl.webfactional.com/timelines/rockpop/test/video/timeline.html
It seems to work as you would hope in Firefox 3.6.15, stopping when you go to the next card.

In Chrome 17.0.963.78, it keeps playing but when you come back you can stop it fine. 

But it's definitely acting up in Safari 5.0.6. When you go to the next card, the audio continues. When you come back to it, the YouTube controls are there, but not video.

Need to roll this timeline out with a project later this week, so may skip the video for now and come back to it on another project.

**Comment by tommeagher** [comment]
OK. It works fine in Firefox 3.6.13 on Mac and 3.6.15 on PC. It works fine in Safari 5.1.2 on Mac. It works fine on IE8.
This bug seems peculiar to Safari 5.0.6, and not even all YouTube videos. Some seem to work OK, while others go blank. Very weird.
