### ISSUE TITLE
Do the zoom arrow buttons work in Chrome?

### ISSUE THREAD

**Issue by palewire** [propublica/timeline-setter#4]
Not showing up for me. Come in fine for Firefox.

**Comment by ashaw** [comment]
They show up in Chrome here: http://propublica.github.com/timeline-setter/doc/timeline-sample.html . Are you getting any JS errors in your local implementation?

**Comment by palewire** [comment]
It must have been some HTML bug I introduced. As soon as I rewrote the unminified HTML template for my own layout, they started to work. Never did figure out what I farked up.
