### ISSUE TITLE
Cards overflow the container and get cut off

### ISSUE THREAD

**Issue by Kirkman** [propublica/timeline-setter#40]
I am just finishing up my first timelines using timeline-setter. I have one into one problem: 

Some of the cards (but not all) overflow the timeline container, even though I set explicit widths and heights on all the HTML elements. (all are either youtube embeds or imgs)

Can anyone tell me what's wrong? 

http://dl.dropbox.com/u/27409695/titanicOut/titanic-timeline-problem.html

**Comment by thejefflarson** [comment]
Those cards are too big to be flipped so, the timeline can't flip them, because they'd still be cut off. You can trigger a zoom and it'll be smarter about things. Or you can make the timelines bigger and/or the pictures smaller.

**Comment by Kirkman** [comment]
How do I trigger a zoom if my var is timeline1? timeline1.zoom("in")?

**Comment by thejefflarson** [comment]
try `$("#timeline1 .TS-zoom_in").click();` after the timeline has loaded. So:

```
timeline1.api.onLoad(function() {
   $("#timeline1 .TS-zoom_in").click()
});
```

**Comment by Kirkman** [comment]
Many thanks!
