### ISSUE TITLE
Feature Request: Unique ID for timeline cards

### ISSUE THREAD

**Issue by drewgeraets** [propublica/timeline-setter#41]
Would be nice to have the ability to style each card differently in the CSS. Could you auto-generate one or have an optional field in the CSV where you could add it? Thoughts? Let me know if this is already possible and I'm just missing it.

**Comment by ashaw** [comment]
You should be able to do this by selecting on `data-timestamp`, for example

```
.TS-item[data-timestamp=727333200000] { 
  background-color: papayaWhip;
}
```

**Comment by drewgeraets** [comment]
Thanks Al. Did that, which worked once I added quotes around the value. Would be nice to just have the timestamp available as an ID?

**Comment by ashaw** [comment]
Good idea.. I'll throw that in there in the next release. In the meantime, you can probably add it to the JS templates in your copy.
