### ISSUE TITLE
Store custom styles in a separate stylesheet

### ISSUE THREAD

**Issue by drewgeraets** [propublica/timeline-setter#42]
Wondering if it'd be better to include custom styles as a separate stylesheet. This would reduce the risk for accidentally overwriting your changes and also make it easier to pull in any updates from the latest release.

Suggested logic: If custom.css exists, include it in the head under stylesheets/timeline-setter.css. 

I'm just starting to learn Ruby so maybe I'll fork and take a crack at it this weekend or next week. 

Thoughts?

**Comment by thejefflarson** [comment]
Sorry for the really late response, but because timelines are meant to be embedded you're totally able to include your own styles in the html, it is encouraged.
