### ISSUE TITLE
JS error with duplicate timestamps while setting intervals in a series

### ISSUE THREAD

**Issue by mleggett** [propublica/timeline-setter#45]
I've run into an issue where a series results in the var intvl being undefined on line 416 of timelineSetter.js.  Since a method is called in it:
date["set" + intvl](date["get" + intvl]()
JS evaluation halts at that point and the timeline fails to render.  The error is reported like so in Chrome:

Uncaught TypeError: Property 'getundefined' of object Wed May 17 2006 17:00:00 GMT-0700 (PDT) is not a function

and FF:

date["get" + intvl] is not a function

Oddly, this only occurs in a production env where the JS is 'minified', making this a little bit difficult to debug.  It's also on a non-public website so I unfortunately can't point you to a live example.  I'll try instead to provide as much information as possible.

At the time the error occurs, the state of the app looks like this:

this.idx: -1
this.INTERVAL_ORDER[this.idx]: undefined
this.max - this.min > this.INTERVALS[e]: false
this.max: 1147910400000
this.min: 1147910400000
this.data: Array[1]
  0: Object
  date: "05/18/2006"
  ...

So what's happening is computeMaxInterval() is returning -1.  It does this because the times are the same in the calculation run in isAtLeastA():
if (!this.isAtLeastA(this.INTERVAL_ORDER[i])) break;

At that point, the interval type is set to the -1 index, which doesn't exist, so it's undefined.  I've plugged the hole in my app but making sure that this.idx is set to 0 if it is less than 0 when the ceil() function is run.  I haven't grokked the script well enough yet to understand why the timestamps for max and min are equal in this case or why I can't reproduce this in a QA environment where the data is (theoretically) the same.  

The issue is reliably reproduced in production with certain data sets.  Could it be a series with only one entry or something similar?

**Comment by thejefflarson** [comment]
Is it possible to provide a simple test case?
