### ISSUE TITLE
Notch position appears to be slightly off

### ISSUE THREAD

**Issue by palewire** [propublica/timeline-setter#5]
Here's a screenshot I took of your Twitter example in Chrome for Linux. See how the data says 5 pm but the notch appears after the hour.

http://www.twitpic.com/4f582g/full

**Comment by thejefflarson** [comment]
Sheesh, well that was a bug, fixed it in:

https://github.com/propublica/timeline-setter/commit/d9399e1aa4f048b35667de0907ae71147dd978ac
