### ISSUE TITLE
When you doubleclick zoom, I think the timeline should also recenter on the spot you clicked.

### ISSUE THREAD

**Issue by palewire** [propublica/timeline-setter#6]
FWIW, that is the behavior of the nytimes timeline.
Right now, if I double click on the far left part of the bar, it seems to just center in the middle-ish area.

**Comment by thejefflarson** [comment]
It actually just tries to keep the current card visible, which I think is a bit more intuitive, e.g. it would be a tad confusing if you clicked on the bar to zoom in and the current item swooped out of the viewport.
