### ISSUE TITLE
Is it possible to layout a two-column card label?

### ISSUE THREAD

**Issue by palewire** [propublica/timeline-setter#7]
With the content on the left, HTML block on the right? I suppose a card without HTML would need to revert to a single column.

The JS is intertwined with the Card's label CSS a bit and I'm not sure exactly how I'd make this fly.

**Comment by palewire** [comment]
Fiddling with it a bit, I rewrote the JS card formatting to be more two-column ish. How crazy is something like:

<pre><code>      var standard_width = this.$(".TS-item_wrapper").width();
      var right_column = this.$(".TS-item_user_html");
      if (right_column) {
          var max = _.max(_.toArray(this.$(".TS-item_user_html").children()), function(el){ return $(el).width(); });
          var right_column_width = $(max).width();
          var left_column_width = this.$(".TS-item_description").width();
          this.$(".TS-item_label").css("width", right_column_width + left_column_width + 20);
      } else {
        this.$(".TS-item_label").css("width", standard_width);
      }</code></pre>

**Comment by thejefflarson** [comment]
Hmm, is there a reason you can't pass in a custom html and set a left and
a right, for example suppose you had the following html:

```
<div class="cont" style="width:300px">
  <div class="left">
    On the left!
  </div>
  <div class="right">
    On the right!
  </div>
</div>
```

and the CSS:

```
.cont * {
  width: 50%;
}

.cont .left{
  float:left;
}

.cont .right{
  float: right;
}
```

wouldn't that solve the problem if you left the label field blank?

Heck you could even rewrite the template to do that for you I bet. The only requirement is that `.TS-item_label` has a child element called `.TS-item_html`.

**Comment by palewire** [comment]
I can't expect my entrants to put more than an <img> or youtube embed in that html field in Excel, so having layout code in there is probably a no-go. 

I'll see if I can fiddle with the template along your lines a bit today. I'll stumble my way to the finish line. I'm whining along the way.

**Comment by thejefflarson** [comment]
Oh totally, what I meant was you could do this in the template and it'd probably work:

```
<div class="TS-item-label">
  <div class="cont" style="width:300px">
    <div class="left">
      <%= card.read("html") %>
    </div>
    <div class="right">
      <%= card.read("label") %>
    </div>
  </div>
</div>
```
